"""Install the dispatcher auto-loader into AutoCAD's roamable support folder.

AutoLISP definitions live in a per-document namespace, so a dispatcher loaded
by hand exists only in the drawing that was open at the time. AutoCAD loads
`acaddoc.lsp` once per document from the support file search path, and the
per-user roamable support folder is on that path by default — so writing the
file there makes the dispatcher follow the user into every drawing without any
OPTIONS dialog or registry editing. It is a plain file write, which also means
it works on AutoCAD LT, where ActiveX is unavailable.

Two things make this safe to run unattended on every startup:

  * The generated lines live inside a marked block, so an existing acaddoc.lsp
    keeps whatever else it contains. Re-running replaces the block rather than
    appending a second copy.
  * The block guards its own load with findfile, so a moved or deleted repo
    fails quietly at drawing-open instead of raising an error every time.

The block also adds the repo's lisp-code folder to TRUSTEDPATHS. Without it,
SECURELOAD raises a modal dialog when loading from an untrusted location, and a
modal dialog blocks the IPC channel — the server hangs rather than fails. This
is a real security relaxation: any .lsp/.arx/.fas in that folder will then load
without a warning. Set AUTOCAD_MCP_AUTOLOAD=0 to disable, or run
scripts/install_autoload.py --uninstall to remove it.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

import structlog

log = structlog.get_logger()

# ASCII only: this file is written in the system ANSI codepage, which varies by
# locale, and the markers must survive a round trip on every machine.
BEGIN = ";; >>> autocad-mcp autoload - managed block, edits here are overwritten"
END = ";; <<< autocad-mcp autoload"

_BLOCK_RE = re.compile(
    re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
    re.S,
)


def find_support_dirs() -> list[Path]:
    """Return every per-user roamable AutoCAD support folder.

    Layout is %APPDATA%/Autodesk/AutoCAD <year>/R<rel>/<lang>/Support. Several
    versions commonly coexist; each has its own acaddoc.lsp, so all of them are
    candidates and the block is inert for versions the user never launches.
    """
    appdata = os.environ.get("APPDATA")
    if not appdata:
        return []
    root = Path(appdata) / "Autodesk"
    if not root.is_dir():
        return []
    return sorted(p for p in root.glob("AutoCAD*/R*/*/Support") if p.is_dir())


def render_block(lisp_dir: Path) -> str:
    """Build the managed block for a given lisp-code directory."""
    # Forward slashes are accepted by load and avoid escaping; TRUSTEDPATHS is
    # compared against what AutoCAD stores, so use the native separator there.
    load_path = lisp_dir.as_posix().rstrip("/") + "/"
    trusted = str(lisp_dir).replace("\\", "\\\\")
    return f"""{BEGIN}
;; Loads the AutoCAD MCP dispatcher into every document namespace.
;; Generated by autocad_mcp - see src/autocad_mcp/autoload.py
(setq *mcp-lisp-dir* "{load_path}")
(if (not (vl-string-search (strcase "{trusted}") (strcase (getvar "TRUSTEDPATHS"))))
  (setvar "TRUSTEDPATHS"
    (strcat (getvar "TRUSTEDPATHS")
            (if (> (strlen (getvar "TRUSTEDPATHS")) 0) ";" "")
            "{trusted}"))
)
;; findfile guard: if the repo moved, fail quietly rather than erroring on
;; every drawing that opens.
(if (and (not c:mcp-dispatch)
         (findfile (strcat *mcp-lisp-dir* "mcp_dispatch.lsp")))
  (load (strcat *mcp-lisp-dir* "mcp_dispatch.lsp"))
)
(princ)
{END}
"""


def apply_block(existing: str | None, block: str) -> str:
    """Insert or replace the managed block, preserving everything else."""
    if not existing:
        return block
    if _BLOCK_RE.search(existing):
        # Replace via a callable: the block contains Windows paths, and re.sub
        # would interpret their backslashes as escapes in a string replacement,
        # producing different output on every run and defeating idempotency.
        return _BLOCK_RE.sub(lambda _: block, existing, count=1)
    separator = "" if existing.endswith("\n") else "\n"
    return existing + separator + "\n" + block


def strip_block(existing: str) -> str:
    """Remove the managed block, leaving any user content intact."""
    return _BLOCK_RE.sub("", existing).rstrip() + "\n"


def _read(path: Path, encoding: str) -> str | None:
    if not path.exists():
        return None
    try:
        return path.read_text(encoding=encoding)
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="replace")


def install(lisp_dir: Path, encoding: str = "cp1252") -> list[tuple[Path, str]]:
    """Write the auto-loader into every support folder found.

    Returns (path, action) pairs where action is created/updated/unchanged.
    Never raises for one unwritable folder — a locked or read-only install of an
    old AutoCAD version should not stop the server starting.
    """
    block = render_block(lisp_dir)
    results: list[tuple[Path, str]] = []

    for support in find_support_dirs():
        target = support / "acaddoc.lsp"
        try:
            current = _read(target, encoding)
            updated = apply_block(current, block)
            if current == updated:
                results.append((target, "unchanged"))
                continue
            # AutoCAD reads .lsp in the system ANSI codepage, not UTF-8.
            target.write_text(updated, encoding=encoding)
            results.append((target, "created" if current is None else "updated"))
        except OSError as e:
            log.warning("autoload_install_failed", path=str(target), error=str(e))
            results.append((target, f"failed: {e}"))

    return results


def uninstall(encoding: str = "cp1252") -> list[tuple[Path, str]]:
    """Remove the managed block wherever it was installed."""
    results: list[tuple[Path, str]] = []
    for support in find_support_dirs():
        target = support / "acaddoc.lsp"
        try:
            current = _read(target, encoding)
            if current is None or not _BLOCK_RE.search(current):
                results.append((target, "absent"))
                continue
            remaining = strip_block(current)
            # A file that held nothing but our block is ours to remove.
            if remaining.strip():
                target.write_text(remaining, encoding=encoding)
                results.append((target, "block removed"))
            else:
                target.unlink()
                results.append((target, "file removed"))
        except OSError as e:
            results.append((target, f"failed: {e}"))
    return results
